blog/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^blog/$', 'blog.views.post_list', name='post_list'),
    url(r'^blog/(?P<pk>\d+)/$', 'blog.views.post_detail', name='post_detail'),
    url(r'^blog/(?P<post_pk>\d+)/comments/new/$', 'blog.views.comment_new', name='comment_new'),
]

djangopractice/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse

def hello(request):
    return HttpResponse('''
        <h1>Hello, <a href="http://facebook.com/askdjango/" target="_blank">AskDjango</a></h1>
    ''')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$' , hello),
    url('', include('blog.urls', namespace='blog')),
    url(r'^new/$', 'blog.views.post_new'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    photo = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()

# python3 manage.py makemigrations
# python3 manage.py migrate blog

blog/forms.py
from .models import Post
from .models import Comment
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'message']

class CommentForm2(forms.Form):
    author = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def save(self, commit=True):
        comment = Comment(**self.cleaned_data)
        if commit:
            comment.save()
        return comment

# CommentForm과 CommentFomr2는 완전히 같은 기능을 하는 코드이다.

blog/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
#from django.views.generic import CreateView
from .models import Post
from .forms import PostForm
from .forms import CommentForm2

def post_new(request):
    # http method
    # - GET : 빈 html form 을 보여준다.
    # - POST : 유저가 빈 html form 을 채워서 "입력완료" 버튼을 누르면, 서버로 POST 방식으로 전송이 됩니다.
    # HttpReuqest 를 통해 받을 수 있는 인자
    # - request.GET : QueryDict 이라는 dict 과 유사한 타입
    # - request.POST : QueryDict 이라는 dict 과 유사한 타입
    # - request.FILES : QueryDict 이라는 dict 과 유사한 타입
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            # 방법 1)
            # url = reverse('blog:post_detail', args=[post.pk])
            # return redirect(url)
            # 방법 2)
            # return redirect(post.get_absolute_url())
            # 방법 3)

            messages.success(request, '새로운 포스팅을 등록했습니다.')

            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

def post_list(request):
    post_list = Post.objects.all()
    return render(request, 'blog/post_list.html',{
        'post_list' : post_list,
    })

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {
        'post' : post,
    })

def comment_new(request, post_pk):
#    form = CommentForm()
    try:
        post = Post.objects.get(pk=post_pk)
    except Post.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = CommentForm2(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save
            return redirect(post)
    else:
        form = CommentForm2()

    return render(request, 'blog/comment_form.html', {
        'form': form
    })
# 위와 같은 코드는
# post -new = CreatView.as_view(model=Post, form_class=PostForm)

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<title>AskDjango Blog</title>
<style>
body {
    padding-top: 60px;
    padding-bottom: 60px;
    padding-left: 60px;
    padding-right: 60px;
}
</style>
</head>
<body>
   <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ko_KR/sdk.js#xfbml=1&version=v2.6&appId=1559430574382775";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</html>

blog/templates/blog/comment_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}

<h1> {{ post.title }} </h1>
<img src="{{ post.photo.url }}", height = 40%, width = 40% />
<hr/>
{{ post.content }}
<hr/>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<div class="fb-comments" data-href="{{request.build_absolute_url}}" data-numposts="5"></div>
<a href="{% url "blog:post_list" %}"> 글 목록으로 </a>

{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}

<ul>
{% for post in post_list %}
<li>
    <a href="{% url "blog:post_detail" post.pk %}">


    {{ post.title }}
    </a>
</li>
{% endfor %}
</ul>

{% endblock %}